services:
  postgres:
    image: postgres:15
    container_name: sample-bank-postgres
    environment:
      POSTGRES_DB: sample_bank
      POSTGRES_USER: sample_bank
      POSTGRES_PASSWORD: sample_bank
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
    container_name: sample-bank-app
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - "8080:8080"

volumes:
  postgres_data:
