apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sample-bank.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DB_USERNAME: {{ .Values.db.username | quote }}
  DB_PASSWORD: {{ .Values.db.password | quote }}
