spring.datasource.url=jdbc:postgresql://localhost:5432/sample_bank
spring.datasource.username=sample_bank
spring.datasource.password=sample_bank
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false

