spring.datasource.url=jdbc:postgresql://localhost:5432/sample_bank
spring.datasource.username=sample_bank
spring.datasource.password=sample_bank
spring.jpa.hibernate.ddl-auto=validate
app.security.bootstrap-user.enabled=true
app.security.bootstrap-user.username=user
app.security.bootstrap-user.password=pass
app.security.bootstrap-user.role=USER
