spring.datasource.driver-class-name=org.postgresql.Driver

app.security.jwt.secret=${JWT_SECRET:sample-bank-local-development-secret-must-be-at-least-32-bytes}
app.security.jwt.expires-in-seconds=3600

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

spring.data.web.pageable.default-page-size=5
spring.data.web.pageable.max-page-size=100
