apiVersion: v1
kind: ConfigMap
metadata:
  name: sample-bank-config
  namespace: sample-bank
data:
  SPRING_PROFILES_ACTIVE: prod
  PORT: "8080"
  DB_URL: jdbc:postgresql://host.minikube.internal:5432/sample_bank
---
apiVersion: v1
kind: Secret
metadata:
  name: sample-bank-secrets
  namespace: sample-bank
type: Opaque
stringData:
  DB_USERNAME: sample_bank
  DB_PASSWORD: sample_bank
