package com.mehrdad.sample.bank.core.mapper;

import com.mehrdad.sample.bank.api.dto.account.AccountDto;
import com.mehrdad.sample.bank.core.entity.AccountEntity;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.ReportingPolicy;

import java.util.List;

/**
 * Created by Mehrdad Ghaderi
 */

@Mapper(componentModel = "spring",
        unmappedTargetPolicy = ReportingPolicy.IGNORE)
public interface AccountMapper {

    // DTO -> Entity
    @Mapping(target = "id", ignore = true) // always generated by JPA
    @Mapping(target = "customer", ignore = true)
    @Mapping(target = "version", ignore = true)
    @Mapping(target = "createdAt", ignore = true)
    @Mapping(target = "updatedAt", ignore = true)
    AccountEntity toAccountEntity(AccountDto dto);

    List<AccountEntity> toAccountEntityList(List<AccountDto> dtos);

    // Entity -> DTO
    AccountDto toAccountDto(AccountEntity entity);

    List<AccountDto> toAccountDtoList(List<AccountEntity> entities);
}